name: Nest AI Recorder
version: 0.1.5
slug: nest_ai_recorder
description: Local Nest camera recorder with AI detection and clip export
url: https://github.com/rahul-ambarakonda/nest_ai_recorder
arch:
  - aarch64
  - amd64
init: false
startup: services
boot: auto
host_network: true
map:
  - media:rw
  - config:rw
options:
  config_path: /config/nest_ai_recorder.yaml
schema:
  config_path: str
